import { AI_CONTENT_CONSTANTS } from "../../AiContentSection/constants/AiContent.constants";

export const VIDEO_CONTENT_CONSTANTS = {
  DEFAULT_HORIZONTAL_TEXTS: AI_CONTENT_CONSTANTS.DEFAULT_HORIZONTAL_TEXTS,
  DEFAULT_TITLE: AI_CONTENT_CONSTANTS.DEFAULT_TITLE,
  DEFAULT_DESCRIPTION: AI_CONTENT_CONSTANTS.DEFAULT_DESCRIPTION,
} as const;

export const DEFAULT_VIDEO_ROWS: string[][] = [[], [], []];